# The Netlify configuration file for https://github.com/doodapps/web-coming-soon.
[build]
  # Gatsby deploymnent sequence.
  command = "npm run build"
  publish = "build"

# Various build enhancements
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[dev]
  framework = "#custom"
  targetPort = 3000
  command = "npm start"
